name: Build Android Chrome
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y \
        git \
        curl \
        unzip \
        openjdk-8-jdk \
        wget \
        libc6-i386 \
        lib32stdc++6 \
        lib32z1 \
        libqt5widgets5 \
        libgl1-mesa-dev \
        libglib2.0-dev \
        libx11-dev \
        libxkbcommon-dev \
        libssl-dev \
        libffi-dev \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel
    - name: Clone Chromium repository
      run: git clone https://chromium.googlesource.com/chromium/src.git
    - name: Install depot_tools
      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: Add depot_tools to PATH
      run: echo "export PATH=\$PATH:$(pwd)/depot_tools" >> $GITHUB_ENV
    - name: Install Android SDK
      run: wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip && unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
    - name: Accept Android licenses
      run: yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
    - name: Set up Android environment variables
      run: echo "export ANDROID_SDK_ROOT=\$HOME/android-sdk" >> $GITHUB_ENV
    - name: Build Android Chrome
      run: |
        mkdir -p src/out/Release && \
        gn gen out/Release --args='target_os="android" target_cpu="arm64" android_ndk_root="$HOME/android-sdk/ndk/22.1.7171670" is_component_build=false is_debug=false' && \
        ninja -C out/Release chrome_public_apk
